#pragma once

#define IOCTL_LOAD_KEY \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x100, METHOD_BUFFERED, FILE_WRITE_DATA)

#define IOCTL_START_INITIALIZE \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x101, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_SCAN_PROCESS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x102, METHOD_BUFFERED, FILE_ANY_ACCESS)

#define IOCTL_GET_STATUS \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x103, METHOD_BUFFERED, FILE_READ_DATA)

#define IOCTL_VALIDATE_CLIENT \
    CTL_CODE(FILE_DEVICE_UNKNOWN, 0x104, METHOD_BUFFERED, FILE_READ_DATA)
